artifact_location: file:c:/Users/valdi/Documents/PERSONAL/Data_Sciences/Project/Deploycamp_CAPSTONE/capstone-project/model/mlflow.team-24.com/0
creation_time: 1754066101352
experiment_id: '0'
last_update_time: 1754066101352
lifecycle_stage: active
name: Default
