artifact_uri: file:c:/Users/valdi/Documents/PERSONAL/Data_Sciences/Project/Deploycamp_CAPSTONE/capstone-project/model/mlflow.team-24.com/0/64c71cef88f0400fb5a3580a6699d39d/artifacts
end_time: 1754066807729
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 64c71cef88f0400fb5a3580a6699d39d
run_name: Logistic Regression Hyperparameter Tuning
source_name: ''
source_type: 4
source_version: ''
start_time: 1754066807256
status: 3
tags: []
user_id: valdi
